### PR TITLE
[WIP] Upgrade to Maven

### PR DESCRIPTION
**Pull request by egonw**
- [x] Added `pom.xml` (with BridgeDb 3.0.1)
- [x] `mvn -Dmaven.test.skip=true clean install` works
- [ ] `mvn clean test` works
- [x] add bundle instructions
- [ ] test with GPML2RDF

### CODE REVIEW

**Comment by mkutmon** [comment]
I don't think this will work - I need the library also as a bundle as a dependency for the WikiPathways plugin so I am not sure why you removed the Manifest file?

**Comment by egonw** [comment]
I haven't added the `bundle` bit yet, but the manifest info is now in the pom.xml.

**Comment by egonw** [comment]
@mkutmon, please try `mvn bundle:bundle`.

**Comment by egonw** [comment]
I just rebased it on the latest `master`.

**Comment by egonw** [comment]
Testing almost works. It seems to be some tests are incorrect and there is a file missing from the repository.

**Comment by egonw** [comment]
Part of the failing test is because of a missing file: https://github.com/wikipathways/wikipathways-api-client-java/issues/27

**Pull request merged**
